import 'normalize.css';
import './assets/scss/app.scss';
import "pixi.js";
import { Game } from './ts/Game';
let width = document.body.clientWidth;
let height = document.body.clientHeight;
const game = new Game(width, height, {antialias: true, backgroundColor: 0x4adbe2});
let root = document.getElementById('app') as HTMLElement;
root.appendChild(game.view);
console.log(window.innerHeight, game.view.height);
